name: Publish Translations Package

on:
  push:
    paths:
      - 'translation/**/*'
      - 'translation/*'
    branches:
      - main  # or master, depending on your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Debug Info
        run: |
          echo "Triggered by push to ${{ github.ref }}"
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hit-pay'

      - name: Install dependencies
        working-directory: translation
        run: npm ci || npm install

      - name: Publish package
        working-directory: translation
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
